rticommunity/rtiperftest

build.bat
build.sh
resource/java_scripts/perftest_java.bat
resource/java_scripts/perftest_java.sh
srcCpp/PerftestTransport.cxx
srcCpp/PerftestTransport.h
srcCpp/RTIDDSImpl.cxx
srcCpp/RTIDDSImpl.h
srcCpp03/PerftestTransport.cxx
srcCpp03/PerftestTransport.h
srcCpp03/RTIDDSImpl.cxx
srcCpp03/RTIDDSImpl.h
srcCs/PerftestTransport.cs
srcCs/RTIDDSImpl.cs
srcDoc/release_notes.rst
srcDoc/test_parameters.rst
srcJava/com/rti/perftest/ddsimpl/PerftestTransport.java
srcJava/com/rti/perftest/ddsimpl/RTIDDSImpl.java

- Refactor transport implementation.
- Improve support for TCP
- Add support for TLS
- Add support for DTLS
- Add support for WAN

Refactor transport implementation

---

srcCpp/MessagingIF.h
srcCpp/RTIDDSImpl.cxx
srcCpp/RTIDDSImpl.h
srcCpp/perftest_cpp.h
srcCpp/perftest_publisher.cxx
srcCpp03/MessagingIF.h
srcCpp03/RTIDDSImpl.cxx
srcCpp03/RTIDDSImpl.h
srcCpp03/perftest_cpp.h
srcCpp03/perftest_publisher.cxx
srcCs/MessagingIF.cs
srcCs/RTIDDSImpl.cs
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcIdl/perftest.idl
srcJava/com/rti/perftest/IMessagingWriter.java
srcJava/com/rti/perftest/ddsimpl/RTIDDSImpl.java
srcJava/com/rti/perftest/ddsimpl/RTIPublisher.java
srcJava/com/rti/perftest/harness/AnnouncementListener.java
srcJava/com/rti/perftest/harness/LatencyListener.java
srcJava/com/rti/perftest/harness/PerfTest.java
srcJava/com/rti/perftest/harness/ThroughputListener.java

Modify announcement topic to handle when changing sizes or finishing tests

Modify announcement topic to handle when changing sizes or finishing

---

srcCpp/MessagingIF.h
srcCpp/RTIDDSImpl.cxx
srcCpp/RTIDDSImpl.h
srcCpp/perftest_cpp.h
srcCpp/perftest_publisher.cxx
srcCpp03/MessagingIF.h
srcCpp03/RTIDDSImpl.cxx
srcCpp03/RTIDDSImpl.h
srcCpp03/perftest_cpp.h
srcCpp03/perftest_publisher.cxx
srcCs/MessagingIF.cs
srcCs/RTIDDSImpl.cs
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcIdl/perftest.idl
srcJava/com/rti/perftest/IMessagingWriter.java
srcJava/com/rti/perftest/ddsimpl/RTIDDSImpl.java
srcJava/com/rti/perftest/ddsimpl/RTIPublisher.java
srcJava/com/rti/perftest/harness/AnnouncementListener.java
srcJava/com/rti/perftest/harness/LatencyListener.java
srcJava/com/rti/perftest/harness/PerfTest.java
srcJava/com/rti/perftest/harness/ThroughputListener.java

Reverts rticommunity/rtiperftest#29. The code still needs to handle the "-scan" mode.

Revert "Modify announcement topic to handle when changing sizes or finishing"

---

srcCpp/MessagingIF.h
srcCpp/RTIDDSImpl.cxx
srcCpp/RTIDDSImpl.h
srcCpp/perftest_publisher.cxx
srcCpp03/MessagingIF.h
srcCpp03/RTIDDSImpl.cxx
srcCpp03/RTIDDSImpl.h
srcCpp03/perftest_publisher.cxx
srcCs/MessagingIF.cs
srcCs/RTIDDSImpl.cs
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcJava/com/rti/perftest/IMessagingWriter.java
srcJava/com/rti/perftest/ddsimpl/RTIPublisher.java
srcJava/com/rti/perftest/harness/AnnouncementListener.java
srcJava/com/rti/perftest/harness/PerfTest.java

Unreliable behavior when using Best Effort + Scan in certain architectures (#59)

---

srcCpp/perftest_cpp.h
srcCpp/perftest_publisher.cxx
srcCpp03/perftest_cpp.h
srcCpp03/perftest_publisher.cxx
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcJava/com/rti/perftest/harness/LatencyListener.java
srcJava/com/rti/perftest/harness/PerfTest.java

Maximum Latency is not correctly obtained when the clock has low resolution

---

srcCs/RTIDDSImpl.cs
srcDoc/release_notes.rst

This pull request is coming from the issue #80. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #80

Remove logger device implementation from .Net

---

srcCpp/perftest_cpp.h
srcCpp03/perftest_cpp.h
srcDoc/release_notes.rst

This pull request is coming from the issue #93. When the pull request is merged into "master" the issue will be closed #93.

Compilation error in Certain VxWorks #93

---

srcDoc/release_notes.rst

Reviewed by our technical writer Rachel Korte.

Documentation review

---

srcJava/com/rti/perftest/harness/LatencyListener.java

This pull request is coming from the issue #109 . When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #109 
After reviewing the code we concluded that the formula is correct, therefore this comment is unnecessary and we are removing it.

Unnecessary TODO removed

---

srcCpp/RTIDDSImpl.cxx

This pull request is coming from the issue #125. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #125

Fix issue RTIOsapiAlignment_getAlignmentOf() OSX

---

srcCpp/Infrastructure_micro.h
srcCpp/perftest_publisher.cxx

Spin and SpinPerMicroSecond implementation for micro.

Add spin and spin per microseconds support for micro

---

srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx

This pull request is coming from the issue #131 . When the pull request is merged into "master" the issue will be fixed #131

Added flush after printing the version message

---

resource/recording_service/recordingservice_wrapper.sh

This pull request is coming from the issue #145. When the pull request is merged into "master" the issue will be fixed #145

Fix timeout of recordingservice_wrapper.sh

---

resource/recording_service/recordingservice_cfg.xml
resource/recording_service/recordingservice_wrapper.sh

This pull request is coming from the issue #XX. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #XX

Recording Service

---

srcCpp/RTIRawTransportImpl.cxx

This pull request is coming from the issue #177. When the pull request is merged, the issue will be closed #177

177 Fix -nic for rawTransport

---

srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcJava/com/rti/perftest/harness/PerfTest.java

This pull request is coming from the issue #123. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #123

Display message for Large Data in Subscriber side

---

srcDoc/compilation.rst

This pull request is coming from the issue #165. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #165

Munching documentation

---

srcDoc/command_line_parameters.rst

This pull request is coming from the issue #115. When the pull request is merged into "master" the issue will be closed #155

Fix misspell in documentation

---

srcDoc/release_notes.rst

This pull request is coming from the issue #188. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #188

Add changes in documentation (#188)

---

srcCpp/perftest_publisher.cxx
srcCppCommon/ParameterManager.cxx
srcDoc/command_line_parameters.rst
srcDoc/release_notes.rst

This pull request is coming from the issue #162. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #162

Low resolution clock

---

build.bat
build.sh
srcDoc/release_notes.rst

This pull request is coming from the issue #101. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #101.

Improve documentation about openssl

---

README.md
srcDoc/command_line_parameters.rst
srcDoc/index.rst
srcDoc/tuning_os.rst

This pull request is coming from the issue #87. When the pull request is merged into "master" the issue will be resolved.

Make OS tuning more visible #87

---

srcCppCommon/ParameterManager.cxx
srcCs/PerftestTransport.cs
srcJava/com/rti/perftest/ddsimpl/PerftestTransport.java

This pull request is coming from the issue #197. When the pull request is merged into "master" the issue will be closed.

Improve help for -nic in Micro (#197)

---

srcCpp/Infrastructure_micro.cxx
srcCpp/Infrastructure_micro.h

Fix for issue introduced by fixing #201 in Pull Request #202

Fix compilation issue and warning

---

.vscode/c_cpp_properties.json
srcCpp/RTIDDSImpl.cxx

This pull request is coming from the issue #208.

Deserialize errors for large data

---

srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx

This pull request is coming from the issue #206. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #206

Initial changes to fix reset of CpuMonitor

---

build.bat
build.sh
srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx

Show last commit ID on perftest header

Get commit ID from build.sh

---

resource/routing_service/routingservice_wrapper.sh

Properly cast float to integer

---

srcCpp/RTIDDSImpl.cxx

Fix dynamic data segv

---

build.bat
build.sh
srcDoc/release_notes.rst

This pull request is coming from the issue #222. When the pull request is merged into "master".

Improve error message when nddshome is not found

---

srcCpp03/RTIDDSImpl.cxx
srcDoc/release_notes.rst

This pull request is coming from issue #226. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #226

Avoid propagation of properties

---

build.bat
build.sh
srcDoc/release_notes.rst

This pull request is coming from the issue #232.

#232 Fix wrong spell for customTypeFlatData

---

srcCpp/Infrastructure_micro.cxx
srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcJava/com/rti/perftest/harness/PerfTest.java

This pull request is coming from the issue #261

Ensure discovery is completed for all entities and bugfix for MICRO-2191

---

srcCpp/RTIRawTransportImpl.cxx
srcDoc/release_notes.rst

This pull request is coming from the issue #283 . When the pull request is merged into "master" the issue will be fixed #283

Fixing port calculation of the publisher with multiples subscribers

---

srcDoc/tutorials/performance_validation.rst

This pull request is coming from the issue #293.

Change incorrect links in documentation

---

srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx
srcCs/perftest_publisher.cs
srcDoc/release_notes.rst
srcJava/com/rti/perftest/harness/LatencyListener.java
srcJava/com/rti/perftest/harness/PerfTest.java
srcJava/com/rti/perftest/harness/ThroughputListener.java

This pull request is coming from the issue #303. When the pull request is merged into "master" the issue will be fixed #303

Message at the end of the test when no samples are received (#303)

---

srcCpp03/RTIDDSImpl.cxx
srcDoc/release_notes.rst

This pull request is coming from the issue #306. When the pull request is merged into "master" the issue will be [resolved, closed, fixed] #306

Fix incorrect handle for FlatData in C++ Modern #306

---

srcCpp/RTIDDSImpl.cxx
srcCpp03/RTIDDSImpl.cxx
srcCpp03/perftest_publisher.cxx
srcCppCommon/ParameterManager.cxx
srcDoc/command_line_parameters.rst

This pull request is coming from the issue #302. When the pull request is merged into "master" the issue will be resolved #302.
Note that this issue will be merged into `customer/TRI-AD` not `master`.

"-showResourceLimits" command line parameter.

---

srcCpp/perftest_publisher.cxx
srcCpp03/perftest_publisher.cxx
srcCppCommon/ParameterManager.cxx
srcDoc/command_line_parameters.rst
srcDoc/release_notes.rst

This pull request is coming from the issue #311. When the pull request is merged into "master" the issue will be fixed #311.
This issue will be merged to bugfix/309/sendq-for-Subs, from customer/TRI-AD.

Set Burst Size

---

srcCpp/RTIDDSImpl.cxx
srcCpp/perftest_publisher.cxx
srcCpp03/RTIDDSImpl.cxx
srcCpp03/perftest_publisher.cxx
srcCppCommon/ParameterManager.cxx
srcCs/RTIDDSImpl.cs
srcCs/perftest_publisher.cs
srcDoc/command_line_parameters.rst
srcDoc/release_notes.rst
srcJava/com/rti/perftest/ddsimpl/RTIDDSImpl.java

This pull request is coming from the issue #309. When the pull request is merged into "master" the issue will be fixed #309.
This branch will be merged into `customer/TRI-AD`

-SendQueueSize not correctly propagated (#309)

---

srcCpp/RTIDDSImpl.cxx
srcCpp03/RTIDDSImpl.cxx
srcDoc/release_notes.rst

This pull request is coming from the issue #316 and #317.

Fix Check Consistency error #316 and #317

---

srcCppCommon/ParameterManager.cxx
srcCppCommon/PerftestPrinter.cxx
srcCs/perftest_publisher.cs
srcDoc/command_line_parameters.rst
srcDoc/designDocuments/280-ouput-format.md
srcDoc/release_notes.rst
srcJava/com/rti/perftest/harness/PerfTest.java

This pull request is coming from the issue #280

Change -noPrintHeaders to -noOutputHeaders

---

srcCppCommon/ParameterManager.cxx
srcDoc/release_notes.rst

This pull request is coming from the issue #324.

#324 Fix batchSize parameter manager option

---

srcCpp03/RTIDDSImpl.cxx
srcDoc/release_notes.rst

This pull request is coming from the issue #332.

Dynamic Data performance in C++03

---

srcCs/perftest_publisher.cs

This pull request is coming from the issue #338 . When the pull request is merged into "master" the issue will be resolved #338.

Fix bug cs compilation

---

srcCpp/FileDataLoader.cxx
srcCpp/FileDataLoader.h
srcCpp/Infrastructure_common.cxx
srcCpp/Infrastructure_common.h

This pull request is coming from the issue #341 . When the pull request is merged into "master" the issue will be fixed #341

#341 Moving the type file size variables to long instead of integers

---

srcCpp/Infrastructure_micro.h

This pull request is coming from the internal RTI Jira PERF-198.

PERF-198: Fix Issue compiling against 2.4.x

---

build.bat
build.sh
srcCppCommon/ParameterManager.h
srcDoc/compilation.rst
srcDoc/release_notes.rst

This pull request is coming from the RTI's Jira issue PERF-194.

PERF-194 -- Compilation issues for RTI Micro and QNX

---

srcDoc/examples.rst

This pull request is coming from the Jira issue PERF-213.

PERF-213: Fix documentation issue

---

srcCpp/Infrastructure_common.cxx
srcCpp/Infrastructure_common.h
srcCpp/Infrastructure_micro.cxx
srcDoc/release_notes.rst

This pull request is coming from the Jira issue #PERF-212.

PERF-212: Add checking for ip in -nic for micro

---

srcCpp/perftest_cpp.h
srcCpp/perftest_publisher.cxx
srcCpp03/perftest_cpp.h
srcCpp03/perftest_publisher.cxx
srcCppCommon/PerftestPrinter.cxx
srcCppCommon/PerftestPrinter.h

PerftestPrinter: Use a base class and inheritance to improve extensibility to other formats
